name: Install job

on:
    workflow_call:
      inputs:
        runner:
            type: string
            default: '["self-hosted", "Linux", "X64"]'

jobs:
    install:
        runs-on: ${{ fromJSON(inputs.runner) }}
        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/install
            - run: forge install
              shell: bash