name: Lint job

on:
    workflow_call:
      inputs:
        runner:
            type: string
            default: '["self-hosted", "Linux", "X64"]'

jobs:
    lint:
        runs-on: ${{ fromJSON(inputs.runner) }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install
            - run: npm run lint
            - run: npm run forge:lint
            - run: npm run format:check
            - run: npm run compile