name: Lint job

on:
    workflow_call:
      inputs:
        runner:
            type: string
            default: '[self-hosted, Linux, X64]'

jobs:
    lint:
        runs-on: ${{ inputs.runner }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install
            - run: npm run lint
              shell: bash
            - run: npm run check:format
            - run: npm run compile
              shell: bash